python3 ../../../main_pretrain.py \
    --dataset adv_imagenet \
    --backbone resnet50 \
    --pretrained \
    --data_dir /data2 \
    --train_dir 1K_New/train \
    --val_dir 1K_New/val \
    --subset_class_num 1000 \
    --max_epochs 50 \
    --gpus 4,5 \
    --accelerator gpu \
    --strategy ddp \
    --sync_batchnorm \
    --precision 16 \
    --optimizer sgd \
    --lars \
    --eta_lars 0.001 \
    --exclude_bias_n_norm \
    --scheduler warmup_cosine \
    --lr 0.3 \
    --accumulate_grad_batches 3 \
    --classifier_lr 0.2 \
    --weight_decay 1e-6 \
    --batch_size 350 \
    --num_workers 40 \
    --num_crops_per_aug 1 1\
    --name byol-Pretrainedresnet50-imagenet-50ep-cont. \
    --entity tinghsuan \
    --project solo-learn \
    --wandb \
    --method byol \
    --proj_output_dim 256 \
    --proj_hidden_dim 4096 \
    --pred_hidden_dim 4096 \
    --base_tau_momentum 0.99 \
    --final_tau_momentum 1.0 \
    --momentum_classifier \
    --auto_resume \
    --resume_from_checkpoint ../../../experiment_result/byol/6261s0nf/byol-Pretrainedresnet50-imagenet-50ep-6261s0nf-ep=49.ckpt \
    --save_checkpoint \
    --checkpoint_dir ../../../experiment_result \
    --brightness 0.4 \
    --contrast 0.4 \
    --saturation 0.2 \
    --hue 0.1 \
    --gaussian_prob 1.0 0.1 \
    --solarization_prob 0.0 0.2 \
    #Add attack
    #--dali \